### ISSUE TITLE
SizeRollingLogFile.flush raises NameError if no max_size is set

### ISSUE THREAD

**Issue by dirkbolte** [bdurand/lumberjack#12]
The following code results in a `NameError`:

``` ruby
require 'lumberjack'
Lumberjack::Device::SizeRollingLogFile.new('test.log').flush
```

Backtrace:

<pre>
from /home/dirkbolte/.rvm/gems/ruby-1.9.3-p392/gems/lumberjack-1.0.4/lib/lumberjack/device/size_rolling_log_file.rb:40:in `>'
    from /home/dirkbolte/.rvm/gems/ruby-1.9.3-p392/gems/lumberjack-1.0.4/lib/lumberjack/device/size_rolling_log_file.rb:40:in `roll_file?'
    from /home/dirkbolte/.rvm/gems/ruby-1.9.3-p392/gems/lumberjack-1.0.4/lib/lumberjack/device/rolling_log_file.rb:46:in `before_flush'
    from /home/dirkbolte/.rvm/gems/ruby-1.9.3-p392/gems/lumberjack-1.0.4/lib/lumberjack/device/writer.rb:95:in `block in flush'
    from <internal:prelude>:10:in `synchronize'
    from /home/dirkbolte/.rvm/gems/ruby-1.9.3-p392/gems/lumberjack-1.0.4/lib/lumberjack/device/writer.rb:94:in `flush'
    from (irb):3
    from /home/dirkbolte/.rvm/rubies/ruby-1.9.3-p392/bin/irb:13:in `<main>'
</pre>

I would expect to either have initialize throw an exception if max_size is not set or to have the other functions work with nil.

**Comment by bdurand** [comment]
Lumberjack 2 now delegates log rolling to the standard library `Logger`.
